language: python
dist: xenial

services:
  - docker
  - postgresql

git:
  depth: 3

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: linting
      name: "Flake8"
      python: 3.7
      before_install: skip
      install: pip install flake8
      before_script: skip
      script: flake8
    - stage: deploy
      name: "Build & Push Image"
      before_install: skip
      install: skip
      before_script: skip
      script: docker build -t "$DOCKER_USERNAME/$DOCKER_IMAGE" .
      deploy:
        provider: script
        script: sh travis_deploy.sh
        on:
          tags: true
