version: "3.7"

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  shortener:
    image: phlasch
    command: ./start-shortener.sh
    restart: always
    ports:
      - 8080:8080
    environment:
      PHLASCH_DB_HOST: database
      PHLASCH_DB_PASSWORD: postgres
      PHLASCH_SHORTENER_ORIGIN: http://localhost:9090

  redirector:
    image: phlasch
    command: ./start-redirector.sh
    restart: always
    ports:
      - 9090:8080
    environment:
      PHLASCH_DB_HOST: database
      PHLASCH_DB_PASSWORD: postgres

  stats:
    image: phlasch
    command: ./start-stats.sh
    restart: always
    ports:
      - 7070:8080
    environment:
      PHLASCH_DB_HOST: database
      PHLASCH_DB_PASSWORD: postgres
      PHLASCH_STATS_ORIGIN: http://localhost:9090
