version: "3.7"

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  server:
    image: phlasch:dev
    restart: always
    ports:
      - 8080:8080
    environment:
      PHLASCH_DB_HOST: database
      PHLASCH_DB_PASSWORD: postgres
